// Auto-generated by fetchGithubProjects.js
// Last updated: 2026-07-24T04:47:32.613Z

export const githubProjects = [
  {
    "name": "Portfolio",
    "description": "Modern 3D portfolio website built with React, Three.js, and Framer Motion. Features interactive 3D models, smooth animations, responsive design, and EmailJS contact form integration.",
    "tags": [
      {
        "name": "react",
        "color": "blue-text-gradient"
      },
      {
        "name": "threejs",
        "color": "green-text-gradient"
      },
      {
        "name": "tailwind",
        "color": "pink-text-gradient"
      }
    ],
    "image": "portfolio-project.png",
    "source_code_link": "https://github.com/YashTripathi-19/Portfolio",
    "website_link": "https://github.com/YashTripathi-19/Portfolio",
    "button_text": "Visit Repo",
    "repo_name": "Portfolio"
  },
  {
    "name": "CarbonSync",
    "description": "Emissions-tracking platform connecting companies, auditors, and regulators with Spring Boot REST API, role-based authentication, and CSV/JSON/PDF export for 100+ emission records.",
    "tags": [
      {
        "name": "java",
        "color": "blue-text-gradient"
      },
      {
        "name": "springboot",
        "color": "green-text-gradient"
      },
      {
        "name": "restapi",
        "color": "pink-text-gradient"
      }
    ],
    "image": "carbonsync-project.png",
    "source_code_link": "https://github.com/YashTripathi-19/CarbonSync",
    "website_link": "https://carbon-sync.netlify.app",
    "button_text": "Visit Website",
    "repo_name": "CarbonSync"
  },
  {
    "name": "Auberon Pharmaceuticals",
    "description": "Production-grade pharmaceutical platform with JWT authentication, OTP verification, automated stock management reducing write-offs by 40%, and admin dashboard.",
    "tags": [
      {
        "name": "nodejs",
        "color": "blue-text-gradient"
      },
      {
        "name": "typescript",
        "color": "green-text-gradient"
      },
      {
        "name": "jwt",
        "color": "pink-text-gradient"
      }
    ],
    "image": "auberon-pharmaceuticals-project.png",
    "source_code_link": "https://github.com/YashTripathi-19/Auberon-Pharmaceuticals",
    "website_link": "https://auberon-pharma.vercel.app",
    "button_text": "Visit Website",
    "repo_name": "Auberon-Pharmaceuticals"
  },
  {
    "name": "Block Chained To Do List",
    "description": "Decentralized task-management DApp built on Ethereum with Solidity smart contracts as the backend logic layer, ensuring secure, immutable task storage.",
    "tags": [
      {
        "name": "solidity",
        "color": "blue-text-gradient"
      },
      {
        "name": "ethereum",
        "color": "green-text-gradient"
      },
      {
        "name": "web3js",
        "color": "pink-text-gradient"
      }
    ],
    "image": "block-chained-to-do-list-project.png",
    "source_code_link": "https://github.com/YashTripathi-19/Block-Chained-To-Do-List",
    "website_link": "https://github.com/YashTripathi-19/Block-Chained-To-Do-List",
    "button_text": "Visit Repo",
    "repo_name": "Block-Chained-To-Do-List"
  },
  {
    "name": "Explore More Projects",
    "description": "Visit my GitHub profile to explore 4+ repositories including backend APIs, microservices, database projects, and more. Each project demonstrates production-ready code, clean architecture, and modern development practices.",
    "tags": [
      {
        "name": "4+ repos",
        "color": "blue-text-gradient"
      },
      {
        "name": "opensource",
        "color": "green-text-gradient"
      },
      {
        "name": "backend",
        "color": "pink-text-gradient"
      }
    ],
    "image": "github-project.png",
    "source_code_link": "https://github.com/YashTripathi-19",
    "website_link": "https://github.com/YashTripathi-19?tab=repositories",
    "button_text": "Visit GitHub",
    "is_github_card": true
  }
];
