// Auto-generated by fetchGithubProjects.js
// Last updated: 2026-07-24T05:17:03.835Z

export const githubProjects = [
  {
    "name": "Portfolio",
    "description": "Modern 3D portfolio website showcasing backend development projects",
    "tags": [
      {
        "name": "javascript",
        "color": "blue-text-gradient"
      }
    ],
    "image": "portfolio-project.png",
    "source_code_link": "https://github.com/YashTripathi-19/Portfolio",
    "website_link": "https://github.com/YashTripathi-19/Portfolio",
    "button_text": "Visit Repo",
    "repo_name": "Portfolio"
  },
  {
    "name": "basic portfolio",
    "description": "A project showcasing development skills and best practices.",
    "tags": [
      {
        "name": "css",
        "color": "blue-text-gradient"
      }
    ],
    "image": "basic-portfolio-project.png",
    "source_code_link": "https://github.com/YashTripathi-19/basic-portfolio",
    "website_link": "https://github.com/YashTripathi-19/basic-portfolio",
    "button_text": "Visit Repo",
    "repo_name": "basic-portfolio"
  },
  {
    "name": "Explore More Projects",
    "description": "Visit my GitHub profile to explore 16+ repositories including backend APIs, microservices, database projects, and more. Each project demonstrates production-ready code, clean architecture, and modern development practices.",
    "tags": [
      {
        "name": "16+ repos",
        "color": "blue-text-gradient"
      },
      {
        "name": "opensource",
        "color": "green-text-gradient"
      },
      {
        "name": "backend",
        "color": "pink-text-gradient"
      }
    ],
    "image": "github-project.png",
    "source_code_link": "https://github.com/YashTripathi-19",
    "website_link": "https://github.com/YashTripathi-19?tab=repositories",
    "button_text": "Visit GitHub",
    "is_github_card": true
  }
];
